### PR TITLE
feat: add storeResults and loadResults generics

### PR DESCRIPTION
**Pull request by jorainer**
As a background info/use case: in xcms we want to allow users to store/load the *result* objects (which are `MsExperiment` and `XcmsExperiment` objects) during or after the analysis in different formats to allow an integration of the data/results in other (external) software. On top of the plain RData format, that can only be read/used by R, we also have plain text file formats (for better/safer Galaxy integration) and @philouail is also working on a MzTab-M export (/import).

These methods should provide a *unified* interface for these operations. The user could e.g. export the data in plain text format, or MzTab format using:

```r
storeResults(xmse, param = PlainTextParam())
storeResults(xmse, param = MzTabParam())
```

Also, we then plan to have something like

```r
loadResults(SummarizedExperiment(), param = MzTabParam())
```

to allow import of results from other software into R. The reason to add these into ProtGenerics is that we need to have these methods also implemented for `Spectra`, `MsBackendMzR` etc.

### CODE REVIEW

**Comment by lgatto** [comment]
Could you clarify what you mean by *import* and *export*? 

- Is *import* adding an external file or a variable to an `MsExperiment` object?
- Is *export* serialising an result from an `MsExperiment` object?

**Comment by jorainer** [comment]
Sorry, did not describe properly. 

- `storeResults()` is saving the object to disk. Similar to what `save()` does, only that we can configure the *type* of the stored file with the second parameter `param`.
- `loadResults()` is *restoring* a previously saved object - or importing a result (created using an external software) as an R object. For the latter case, `loadResults(SummarizedExperiment(), param = MzTabParam(), file = "test.mztab")` would import the data from the file in mzTab-M format and putting its content into a `SummarizedExperiment` - which is then returned.

The names of the methods can be changed, obviously, the key is that we want to have a dispatch on `object` and `param` to support various file types and objects.

**Comment by jorainer** [comment]
As described above, the general idea is to have a method that allows storing and restoring objects (data), similar to what would be possible with `save` and `load`, only that I wanted to be able to specify the "storage mode" for the exported data and also specify the object that should be restored/imported: `storeResults(spectra_object, PlainTextParam("path to the export directory"))` and `loadResults(Spectra(), PlainTextParam("path to the export directory"))`.

This will be some key functionality we will use in `xcms` and then also in `Spectra` et al. Question is however the name of the methods... `storeResults` and `loadResults` might be misleading maybe? Or maybe better `storeObject`/`restoreObject` to make it explicit that the object is exported and can later be restored, so, not "only" the data. alternative suggestions welcome @lgatto @philouail.

**Comment by philouail** [comment]
Actually I agree on the use of the word `object` in the function name, as it also highlights that the user can save at any point during the analysis. 

Maybe we can also highlight that this method allows save and load in different computer system, which is what I had been struggling with and we have add some comments from user also asking for a similar thing. The parameter `spectraPath` in `loadResults()` allows to do just that. We change the `dataStorageBasePath() `of the object essentially.

**Comment by jorainer** [comment]
But then, what's better in terms of intuitiveness to the user: `storeObject()`/`restoreObject()` or `saveObject()`/`loadObject()`? I'm OK with both, but used *store* initially to make clear we want to support "permanently" saving an object - but that it can still be loaded later (with `save()`/`load()` that might not always work, e.g. if the exported class was updated or if there was some major change in R).

**Comment by lgatto** [comment]
I think I understand and support the basic idea, i.e. serialising result objects that live in an `MsExperiment` object, and importing a result from a file into an `MsExperiment` object. This needs to be flexible, as the file can be of different formats, and the result object of different types. 

But I don't really like the fact that your suggestion combines two things that, in my opinion should be separate:

1. accessing/setting the result slot of the `MsExperiment` object
2. serialising/import data to/from a file.

I would prefer the following paradigm:

```
resultObject(mse) |> save() ## or export() ... whatever is fit
```

and

```
resultObject(mse) <- load() ## or import() ... whatever is fit
```

The reasons I prefer this are:

- I think this is more in line with the general R syntax.
- The serialisation and importing/loading could be externalised into a new package (`MsIO` for example), that takes these different cases and functions into account. 

Open to discuss this, of course.

**Comment by jorainer** [comment]
No, sorry, I was not clear - and the initial name that contained *Results* was definitely misleading. I don't what to do point 1 (accessing or setting the result slot of any object), I just want to do point 2, serializing/importing an object (or rather the content of an object) to disk. For that I want to have a second parameter that allows to define the format in which the data/object gets stored.

Example (export to text file(s)):

```r
saveObject(mse, param = PlainTextParam(path = "<directory where to store the data>"))
mse <- loadObject(MsExperiment(), param = PlainTextParam(path = "<directory where the data was stored>"))
```

Internally, the `saveObject,MsExperiment` should then call `saveObject,Spectra`/`saveObject,MsBackend` etc.

While writing this, maybe a method name like `writeObject()`/`readObject()` might even be better...

**Comment by jorainer** [comment]
Closing in favor of a dedicated *MsIO* package that contains the code/functionality to save/read MS-related data (S4) objects.

**Comment by lgatto** [comment]
For future reference: https://bioconductor.org/packages/release/bioc/html/alabaster.base.html

**Pull request closed without merging**
