### PR TITLE
Add setter generics for all generic names

### PR DESCRIPTION
**Pull request by thomasp85**
In general, while I think it might not always make sense, I think there should be available setters for every getter generic.

### CODE REVIEW

**Comment by lgatto** [comment]
I am afraid I strongly disagree. 

First, these generics are not necessarily accessors. They might be in some cases/classes, but don't have to be. 

In addition, I believe there isn't a need for setters for all slots, as this could so easily lead to breaking the object's validity. Updating the _"raw"_ data is not a good idea; 
if one wants a new object (i.e. with updated data), then there should be a function that transforms the data, constructs a new object, and returns it. There shouldn't be an easy way for a user to break their data nilly willy.

Do you have some specific use-cases in mind?

**Comment by thomasp85** [comment]
My main example is in MSGFplus where the search parameters can be build up gradually, adding modifications and database with the respective setters.

I don't think your examples are valid as it is up to the designer of a class to evaluate whether setters should be provided or not and how to handle validity. Making these available in ProtGenerics doesn't force anyone to have both getters and setters for any class. I agree that they wouldn't make sense for a lot of data representations both then they just shouldn't be implemented for these classes...

/Thomas

**Comment by lgatto** [comment]
> My main example is in MSGFplus where the search parameters can be build up gradually, adding modifications and database with the respective setters.

Then go ahead and create these specific replacement functions. If more cases and conflicts appear, then it will be time to harmonise signatures and migrate. Most of the current generics had methods in several packages, triggering the need for `ProtGenerics`.

**Comment by thomasp85** [comment]
I'll do that then - I just added the rest as I thought their omission was a slip. I still can't see a logic reason for not having them there - they might provide a future namespace clash and even incentives developer to create proper setters for their classes instead of relying on users using the @-accessor, which I think we can both agree is bad. 

Anyway that is your call - I'll make a new PR

**Comment by thomasp85** [comment]
Closed in favour of #2 with less setters

**Pull request closed without merging**
