### PR TITLE
Add MSGFplus setters

### PR DESCRIPTION
**Pull request by thomasp85**

### CODE REVIEW

**Comment by lgatto** [comment]
I was not clear... add these generics in `MSGFplus`. 

`ProtGenerics` is not the central package for generics or should stop you from defining the generics you need. It is a means to centralise generics that are repeatedly used in different packages (for example `mzR::psms` and `mzID::psms`, or `IRanges::score` and `mzR::score`, now `BioGenerics::score`) or generic in a rather big package (say `mzR`) on which one wouldn't want to depend just for the sake of that generic's definition. 

In case a conflict appeared, we could (1) add these same definitions in `ProtGenerics`; (2) remove them from `MSGFplus` and import `ProtGenerics`. This would be very minor/straightforward changes for you and would resolve issues if they arose.

**Comment by thomasp85** [comment]
I misunderstood your intensions with this package then - I'll wait for namespace conflicts before adding anything in the future...

**Comment by lgatto** [comment]
And the premise is that conflict are relatively rare :-)

**Comment by lgatto** [comment]
Just a clarification, here. IMHO, an essential aspect of our efforts is open development and giving developers the freedom of implementing things the way they see it. A central/unique package for generics would stand in the way is this. The goal of `ProtGenerics` is to step in when namespace conflicts arise, to facilitate interoperation of packages. 

I shall clarify this in a README file.

**Pull request closed without merging**
